var 0..1: v1; var 0..1: n_v1;
constraint v1 + n_v1 = 1;

var 0..1: v2; var 0..1: n_v2;
constraint v2 + n_v2 = 1;

var 0..1: v3; var 0..1: n_v3;
constraint v3 + n_v3 = 1;

var 0..1: v4; var 0..1: n_v4;
constraint v4 + n_v4 = 1;

var 0..1: v5; var 0..1: n_v5;
constraint v5 + n_v5 = 1;

var 0..1: v6; var 0..1: n_v6;
constraint v6 + n_v6 = 1;

var 0..1: v7; var 0..1: n_v7;
constraint v7 + n_v7 = 1;

var 0..1: v8; var 0..1: n_v8;
constraint v8 + n_v8 = 1;

var 0..1: v9; var 0..1: n_v9;
constraint v9 + n_v9 = 1;

var 0..1: v10; var 0..1: n_v10;
constraint v10 + n_v10 = 1;

var 0..1: v11; var 0..1: n_v11;
constraint v11 + n_v11 = 1;

var 0..1: v12; var 0..1: n_v12;
constraint v12 + n_v12 = 1;

var 0..1: v13; var 0..1: n_v13;
constraint v13 + n_v13 = 1;

var 0..1: v14; var 0..1: n_v14;
constraint v14 + n_v14 = 1;

var 0..1: v15; var 0..1: n_v15;
constraint v15 + n_v15 = 1;

var 0..1: v16; var 0..1: n_v16;
constraint v16 + n_v16 = 1;

var 0..1: v17; var 0..1: n_v17;
constraint v17 + n_v17 = 1;

var 0..1: v18; var 0..1: n_v18;
constraint v18 + n_v18 = 1;

var 0..1: v19; var 0..1: n_v19;
constraint v19 + n_v19 = 1;

var 0..1: v20; var 0..1: n_v20;
constraint v20 + n_v20 = 1;

var 0..1: v21; var 0..1: n_v21;
constraint v21 + n_v21 = 1;

var 0..1: v22; var 0..1: n_v22;
constraint v22 + n_v22 = 1;

var 0..1: v23; var 0..1: n_v23;
constraint v23 + n_v23 = 1;

var 0..1: v24; var 0..1: n_v24;
constraint v24 + n_v24 = 1;

var 0..1: v25; var 0..1: n_v25;
constraint v25 + n_v25 = 1;

var 0..1: v26; var 0..1: n_v26;
constraint v26 + n_v26 = 1;

var 0..1: v27; var 0..1: n_v27;
constraint v27 + n_v27 = 1;

var 0..1: v28; var 0..1: n_v28;
constraint v28 + n_v28 = 1;

var 0..1: v29; var 0..1: n_v29;
constraint v29 + n_v29 = 1;

var 0..1: v30; var 0..1: n_v30;
constraint v30 + n_v30 = 1;

var 0..1: v31; var 0..1: n_v31;
constraint v31 + n_v31 = 1;

var 0..1: v32; var 0..1: n_v32;
constraint v32 + n_v32 = 1;

var 0..1: v33; var 0..1: n_v33;
constraint v33 + n_v33 = 1;

var 0..1: v34; var 0..1: n_v34;
constraint v34 + n_v34 = 1;

var 0..1: v35; var 0..1: n_v35;
constraint v35 + n_v35 = 1;

var 0..1: v36; var 0..1: n_v36;
constraint v36 + n_v36 = 1;

var 0..1: v37; var 0..1: n_v37;
constraint v37 + n_v37 = 1;

var 0..1: v38; var 0..1: n_v38;
constraint v38 + n_v38 = 1;

var 0..1: v39; var 0..1: n_v39;
constraint v39 + n_v39 = 1;

var 0..1: v40; var 0..1: n_v40;
constraint v40 + n_v40 = 1;

var 0..1: v41; var 0..1: n_v41;
constraint v41 + n_v41 = 1;

var 0..1: v42; var 0..1: n_v42;
constraint v42 + n_v42 = 1;

var 0..1: v43; var 0..1: n_v43;
constraint v43 + n_v43 = 1;

var 0..1: v44; var 0..1: n_v44;
constraint v44 + n_v44 = 1;

var 0..1: v45; var 0..1: n_v45;
constraint v45 + n_v45 = 1;

var 0..1: v46; var 0..1: n_v46;
constraint v46 + n_v46 = 1;

var 0..1: v47; var 0..1: n_v47;
constraint v47 + n_v47 = 1;

var 0..1: v48; var 0..1: n_v48;
constraint v48 + n_v48 = 1;

var 0..1: v49; var 0..1: n_v49;
constraint v49 + n_v49 = 1;

var 0..1: v50; var 0..1: n_v50;
constraint v50 + n_v50 = 1;

var 0..1: v51; var 0..1: n_v51;
constraint v51 + n_v51 = 1;

var 0..1: v52; var 0..1: n_v52;
constraint v52 + n_v52 = 1;

var 0..1: v53; var 0..1: n_v53;
constraint v53 + n_v53 = 1;

var 0..1: v54; var 0..1: n_v54;
constraint v54 + n_v54 = 1;

var 0..1: v55; var 0..1: n_v55;
constraint v55 + n_v55 = 1;

var 0..1: v56; var 0..1: n_v56;
constraint v56 + n_v56 = 1;

var 0..1: v57; var 0..1: n_v57;
constraint v57 + n_v57 = 1;

var 0..1: v58; var 0..1: n_v58;
constraint v58 + n_v58 = 1;

var 0..1: v59; var 0..1: n_v59;
constraint v59 + n_v59 = 1;

var 0..1: v60; var 0..1: n_v60;
constraint v60 + n_v60 = 1;

var 0..1: v61; var 0..1: n_v61;
constraint v61 + n_v61 = 1;

var 0..1: v62; var 0..1: n_v62;
constraint v62 + n_v62 = 1;

var 0..1: v63; var 0..1: n_v63;
constraint v63 + n_v63 = 1;

var 0..1: v64; var 0..1: n_v64;
constraint v64 + n_v64 = 1;

var 0..1: v65; var 0..1: n_v65;
constraint v65 + n_v65 = 1;

var 0..1: v66; var 0..1: n_v66;
constraint v66 + n_v66 = 1;

var 0..1: v67; var 0..1: n_v67;
constraint v67 + n_v67 = 1;

var 0..1: v68; var 0..1: n_v68;
constraint v68 + n_v68 = 1;

var 0..1: v69; var 0..1: n_v69;
constraint v69 + n_v69 = 1;

var 0..1: v70; var 0..1: n_v70;
constraint v70 + n_v70 = 1;

var 0..1: v71; var 0..1: n_v71;
constraint v71 + n_v71 = 1;

var 0..1: v72; var 0..1: n_v72;
constraint v72 + n_v72 = 1;

var 0..1: v73; var 0..1: n_v73;
constraint v73 + n_v73 = 1;

var 0..1: v74; var 0..1: n_v74;
constraint v74 + n_v74 = 1;

var 0..1: v75; var 0..1: n_v75;
constraint v75 + n_v75 = 1;

var 0..1: v76; var 0..1: n_v76;
constraint v76 + n_v76 = 1;

var 0..1: v77; var 0..1: n_v77;
constraint v77 + n_v77 = 1;

var 0..1: v78; var 0..1: n_v78;
constraint v78 + n_v78 = 1;

var 0..1: v79; var 0..1: n_v79;
constraint v79 + n_v79 = 1;

var 0..1: v80; var 0..1: n_v80;
constraint v80 + n_v80 = 1;

var 0..1: v81; var 0..1: n_v81;
constraint v81 + n_v81 = 1;

var 0..1: v82; var 0..1: n_v82;
constraint v82 + n_v82 = 1;

var 0..1: v83; var 0..1: n_v83;
constraint v83 + n_v83 = 1;

var 0..1: v84; var 0..1: n_v84;
constraint v84 + n_v84 = 1;

var 0..1: v85; var 0..1: n_v85;
constraint v85 + n_v85 = 1;

var 0..1: v86; var 0..1: n_v86;
constraint v86 + n_v86 = 1;

var 0..1: v87; var 0..1: n_v87;
constraint v87 + n_v87 = 1;

var 0..1: v88; var 0..1: n_v88;
constraint v88 + n_v88 = 1;

var 0..1: v89; var 0..1: n_v89;
constraint v89 + n_v89 = 1;

var 0..1: v90; var 0..1: n_v90;
constraint v90 + n_v90 = 1;

var 0..1: v91; var 0..1: n_v91;
constraint v91 + n_v91 = 1;

var 0..1: v92; var 0..1: n_v92;
constraint v92 + n_v92 = 1;

var 0..1: v93; var 0..1: n_v93;
constraint v93 + n_v93 = 1;

var 0..1: v94; var 0..1: n_v94;
constraint v94 + n_v94 = 1;

var 0..1: v95; var 0..1: n_v95;
constraint v95 + n_v95 = 1;

var 0..1: v96; var 0..1: n_v96;
constraint v96 + n_v96 = 1;

var 0..1: v97; var 0..1: n_v97;
constraint v97 + n_v97 = 1;

constraint n_v1 + n_v13 + n_v57 >= 1;
constraint n_v1 + n_v13 + n_v69 >= 1;
constraint n_v1 + n_v57 + n_v69 >= 1;
constraint n_v13 + n_v57 + n_v69 >= 1;
constraint n_v29 + n_v77 + n_v85 >= 1;
constraint n_v29 + n_v77 + n_v89 >= 1;
constraint n_v29 + n_v85 + n_v89 >= 1;
constraint n_v77 + n_v85 + n_v89 >= 1;
constraint n_v2 + n_v9 + n_v17 >= 1;
constraint n_v2 + n_v9 + n_v73 >= 1;
constraint n_v2 + n_v17 + n_v73 >= 1;
constraint n_v9 + n_v17 + n_v73 >= 1;
constraint n_v21 + n_v49 + n_v61 >= 1;
constraint n_v21 + n_v49 + n_v74 >= 1;
constraint n_v21 + n_v61 + n_v74 >= 1;
constraint n_v49 + n_v61 + n_v74 >= 1;
constraint n_v18 + n_v45 + n_v65 >= 1;
constraint n_v18 + n_v45 + n_v90 >= 1;
constraint n_v18 + n_v65 + n_v90 >= 1;
constraint n_v45 + n_v65 + n_v90 >= 1;
constraint n_v3 + n_v46 + n_v53 >= 1;
constraint n_v3 + n_v46 + n_v81 >= 1;
constraint n_v3 + n_v53 + n_v81 >= 1;
constraint n_v46 + n_v53 + n_v81 >= 1;
constraint n_v10 + n_v30 + n_v33 >= 1;
constraint n_v10 + n_v30 + n_v50 >= 1;
constraint n_v10 + n_v33 + n_v50 >= 1;
constraint n_v30 + n_v33 + n_v50 >= 1;
constraint n_v5 + n_v22 + n_v31 >= 1;
constraint n_v5 + n_v22 + n_v66 >= 1;
constraint n_v5 + n_v31 + n_v66 >= 1;
constraint n_v22 + n_v31 + n_v66 >= 1;
constraint n_v4 + n_v25 + n_v34 >= 1;
constraint n_v4 + n_v25 + n_v41 >= 1;
constraint n_v4 + n_v34 + n_v41 >= 1;
constraint n_v25 + n_v34 + n_v41 >= 1;
constraint n_v6 + n_v14 + n_v42 >= 1;
constraint n_v6 + n_v14 + n_v78 >= 1;
constraint n_v6 + n_v42 + n_v78 >= 1;
constraint n_v14 + n_v42 + n_v78 >= 1;
constraint n_v62 + n_v67 + n_v70 >= 1;
constraint n_v62 + n_v67 + n_v82 >= 1;
constraint n_v62 + n_v70 + n_v82 >= 1;
constraint n_v67 + n_v70 + n_v82 >= 1;
constraint n_v54 + n_v58 + n_v63 >= 1;
constraint n_v54 + n_v58 + n_v86 >= 1;
constraint n_v54 + n_v63 + n_v86 >= 1;
constraint n_v58 + n_v63 + n_v86 >= 1;
constraint n_v11 + n_v47 + n_v64 >= 1;
constraint n_v11 + n_v47 + n_v79 >= 1;
constraint n_v11 + n_v64 + n_v79 >= 1;
constraint n_v47 + n_v64 + n_v79 >= 1;
constraint n_v43 + n_v59 + n_v68 >= 1;
constraint n_v43 + n_v59 + n_v75 >= 1;
constraint n_v43 + n_v68 + n_v75 >= 1;
constraint n_v59 + n_v68 + n_v75 >= 1;
constraint n_v19 + n_v26 + n_v32 >= 1;
constraint n_v19 + n_v26 + n_v71 >= 1;
constraint n_v19 + n_v32 + n_v71 >= 1;
constraint n_v26 + n_v32 + n_v71 >= 1;
constraint n_v37 + n_v55 + n_v72 >= 1;
constraint n_v37 + n_v55 + n_v91 >= 1;
constraint n_v37 + n_v72 + n_v91 >= 1;
constraint n_v55 + n_v72 + n_v91 >= 1;
constraint n_v38 + n_v44 + n_v48 >= 1;
constraint n_v38 + n_v44 + n_v51 >= 1;
constraint n_v38 + n_v48 + n_v51 >= 1;
constraint n_v44 + n_v48 + n_v51 >= 1;
constraint n_v7 + n_v27 + n_v52 >= 1;
constraint n_v7 + n_v27 + n_v83 >= 1;
constraint n_v7 + n_v52 + n_v83 >= 1;
constraint n_v27 + n_v52 + n_v83 >= 1;
constraint n_v12 + n_v28 + n_v39 >= 1;
constraint n_v12 + n_v28 + n_v93 >= 1;
constraint n_v12 + n_v39 + n_v93 >= 1;
constraint n_v28 + n_v39 + n_v93 >= 1;
constraint n_v15 + n_v23 + n_v87 >= 1;
constraint n_v15 + n_v23 + n_v94 >= 1;
constraint n_v15 + n_v87 + n_v94 >= 1;
constraint n_v23 + n_v87 + n_v94 >= 1;
constraint n_v24 + n_v56 + n_v80 >= 1;
constraint n_v24 + n_v56 + n_v95 >= 1;
constraint n_v24 + n_v80 + n_v95 >= 1;
constraint n_v56 + n_v80 + n_v95 >= 1;
constraint n_v8 + n_v35 + n_v60 >= 1;
constraint n_v8 + n_v35 + n_v96 >= 1;
constraint n_v8 + n_v60 + n_v96 >= 1;
constraint n_v35 + n_v60 + n_v96 >= 1;
constraint n_v16 + n_v76 + n_v84 >= 1;
constraint n_v16 + n_v76 + n_v92 >= 1;
constraint n_v16 + n_v84 + n_v92 >= 1;
constraint n_v76 + n_v84 + n_v92 >= 1;
constraint n_v20 + n_v36 + n_v40 >= 1;
constraint n_v20 + n_v36 + n_v88 >= 1;
constraint n_v20 + n_v36 + n_v97 >= 1;
constraint n_v20 + n_v40 + n_v88 >= 1;
constraint n_v20 + n_v40 + n_v97 >= 1;
constraint n_v20 + n_v88 + n_v97 >= 1;
constraint n_v36 + n_v40 + n_v88 >= 1;
constraint n_v36 + n_v40 + n_v97 >= 1;
constraint n_v36 + n_v88 + n_v97 >= 1;
constraint n_v40 + n_v88 + n_v97 >= 1;
constraint v1 + v2 + v3 >= 1;
constraint v1 + v2 + v4 >= 1;
constraint v1 + v3 + v4 >= 1;
constraint v2 + v3 + v4 >= 1;
constraint v5 + v6 + v7 >= 1;
constraint v5 + v6 + v8 >= 1;
constraint v5 + v7 + v8 >= 1;
constraint v6 + v7 + v8 >= 1;
constraint v9 + v10 + v11 >= 1;
constraint v9 + v10 + v12 >= 1;
constraint v9 + v11 + v12 >= 1;
constraint v10 + v11 + v12 >= 1;
constraint v13 + v14 + v15 >= 1;
constraint v13 + v14 + v16 >= 1;
constraint v13 + v15 + v16 >= 1;
constraint v14 + v15 + v16 >= 1;
constraint v17 + v18 + v19 >= 1;
constraint v17 + v18 + v20 >= 1;
constraint v17 + v19 + v20 >= 1;
constraint v18 + v19 + v20 >= 1;
constraint v21 + v22 + v23 >= 1;
constraint v21 + v22 + v24 >= 1;
constraint v21 + v23 + v24 >= 1;
constraint v22 + v23 + v24 >= 1;
constraint v25 + v26 + v27 >= 1;
constraint v25 + v26 + v28 >= 1;
constraint v25 + v27 + v28 >= 1;
constraint v26 + v27 + v28 >= 1;
constraint v29 + v30 + v31 >= 1;
constraint v29 + v30 + v32 >= 1;
constraint v29 + v31 + v32 >= 1;
constraint v30 + v31 + v32 >= 1;
constraint v33 + v34 + v35 >= 1;
constraint v33 + v34 + v36 >= 1;
constraint v33 + v35 + v36 >= 1;
constraint v34 + v35 + v36 >= 1;
constraint v37 + v38 + v39 >= 1;
constraint v37 + v38 + v40 >= 1;
constraint v37 + v39 + v40 >= 1;
constraint v38 + v39 + v40 >= 1;
constraint v41 + v42 + v43 >= 1;
constraint v41 + v42 + v44 >= 1;
constraint v41 + v43 + v44 >= 1;
constraint v42 + v43 + v44 >= 1;
constraint v45 + v46 + v47 >= 1;
constraint v45 + v46 + v48 >= 1;
constraint v45 + v47 + v48 >= 1;
constraint v46 + v47 + v48 >= 1;
constraint v49 + v50 + v51 >= 1;
constraint v49 + v50 + v52 >= 1;
constraint v49 + v51 + v52 >= 1;
constraint v50 + v51 + v52 >= 1;
constraint v53 + v54 + v55 >= 1;
constraint v53 + v54 + v56 >= 1;
constraint v53 + v55 + v56 >= 1;
constraint v54 + v55 + v56 >= 1;
constraint v57 + v58 + v59 >= 1;
constraint v57 + v58 + v60 >= 1;
constraint v57 + v59 + v60 >= 1;
constraint v58 + v59 + v60 >= 1;
constraint v61 + v62 + v63 >= 1;
constraint v61 + v62 + v64 >= 1;
constraint v61 + v63 + v64 >= 1;
constraint v62 + v63 + v64 >= 1;
constraint v65 + v66 + v67 >= 1;
constraint v65 + v66 + v68 >= 1;
constraint v65 + v67 + v68 >= 1;
constraint v66 + v67 + v68 >= 1;
constraint v69 + v70 + v71 >= 1;
constraint v69 + v70 + v72 >= 1;
constraint v69 + v71 + v72 >= 1;
constraint v70 + v71 + v72 >= 1;
constraint v73 + v74 + v75 >= 1;
constraint v73 + v74 + v76 >= 1;
constraint v73 + v75 + v76 >= 1;
constraint v74 + v75 + v76 >= 1;
constraint v77 + v78 + v79 >= 1;
constraint v77 + v78 + v80 >= 1;
constraint v77 + v79 + v80 >= 1;
constraint v78 + v79 + v80 >= 1;
constraint v81 + v82 + v83 >= 1;
constraint v81 + v82 + v84 >= 1;
constraint v81 + v82 + v97 >= 1;
constraint v81 + v83 + v84 >= 1;
constraint v81 + v83 + v97 >= 1;
constraint v81 + v84 + v97 >= 1;
constraint v82 + v83 + v84 >= 1;
constraint v82 + v83 + v97 >= 1;
constraint v82 + v84 + v97 >= 1;
constraint v83 + v84 + v97 >= 1;
constraint v85 + v86 + v87 >= 1;
constraint v85 + v86 + v88 >= 1;
constraint v85 + v87 + v88 >= 1;
constraint v86 + v87 + v88 >= 1;
constraint v89 + v90 + v91 >= 1;
constraint v89 + v90 + v92 >= 1;
constraint v89 + v91 + v92 >= 1;
constraint v90 + v91 + v92 >= 1;
constraint v93 + v94 + v95 >= 1;
constraint v93 + v94 + v96 >= 1;
constraint v93 + v95 + v96 >= 1;
constraint v94 + v95 + v96 >= 1;
solve satisfy;